require: rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.3
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
  
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/**'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
    - 'app/controllers/reviews_controller.rb'

Rails/BulkChangeTable:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/*'
